# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe0f8a7c808cee0cee2ceda4da02621991759c04a5dfb862eb3dd1825eecc15f27233aba16ae009a27ca97b597b48ec036919ed1a38b6e1c710c1f0c8286c42

test:
  secret_key_base: bf70d22623327ea55e70d176f568b7bdf9a9619186701a300a33fc7aebb274bdf0ec645a9e58da8d50be7e7c7efd4e4cc16683fba8de568a8a63b7b4546c1a59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
